
public class Problems {
	int sum1 = 0;
	Problems() {
		//problem2(1, 2);
		long p3 = 10086647l; // 10086647 * 839 = 8462696833, 8462696833 * 71 = 600851475143
		//problem3(p3);
		System.out.println("");
		//problem6(100);
		//problem7(10001);
		problem8(13);
	}
	public static void main(String[] args) {
		Problems p = new Problems();
	}
	
	/* PROBLEM 1----------------------------------
	 * If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
	 * The sum of these multiples is 23.
	 * Find the sum of all the multiples of 3 or 5 below 1000.*/
	public void problem1(int range) {
		int sum = 0;
		for (int i = 1; i < range; i++) {
			if (i % 3 == 0 || i % 5 == 0) {
				sum += i;
			}
		}
		System.out.println(sum);
	}
	
	/* PROBLEM 2----------------------------------
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
	 * By starting with 1 and 2, the first 10 terms will be:
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * By considering the terms in the Fibonacci sequence whose values do not exceed 
	 * four million, find the sum of the even-valued terms.*/
	public void problem2(int x, int y) {
		int num = x + y;
	/*	System.out.println(x); */
		if (num > 4000000) { System.out.print("sum= " + (sum1 + 2)); return; }
		if (num % 2 == 0) {
			sum1 += num;
		}
		//System.out.println(x);
		problem2(y, num);
	}
	/* PROBLEM 3-----------------------------------
	 * The prime factors of 13195 are 5, 7, 13 and 29.
    What is the largest prime factor of the number 600,851,475,143 ? */
	// 91 = 7, 13, 
	public void problem3(long num) {
		int answer = 1;
		for (int i = 2; i < num; i++) {
			if(num % i == 0) {
				if(isPrime(i)) {
					answer = i;
				}
			}
		}
		System.out.println("answer= " + answer);
	}
	public boolean isPrime(int n) {
		for(int i = 2; i < n; i++) {
			if(n % i == 0) {
				return false;
			}
		}
		return true;
	}
	/* PROBLEM 4--------------------------
	 * A palindromic number reads the same both ways. 
	 * The largest palindrome made from the product of 
	 * two 2-digit numbers is 9009 = 91 × 99.
	 * Find the largest palindrome made from the product of two 3-digit numbers. */
	 public void problem4() {
		 int ans = 0;
		 for(int i = 100; i < 1000; i++) {
			 for(int j = 100; j < 1000; j++) {
				 int temp = i * j;
				 if(isPalindrome(temp)) {
					 if (temp > ans) {
						 ans = temp;
						 System.out.println(ans);
					 }
				 }
			 }
		 }
		 System.out.println("final answer= " + ans);
	 }
	 public boolean isPalindrome(int num) {
		 String numStr = num + "";
		 for (int i = 0; i < numStr.length() / 2; i++) {
			 char a = numStr.charAt(i);
			 char b = numStr.charAt(numStr.length() - 1 - i);
			 if(a != b) return false; 
		 }
		 return true;
	 }
	/*PROBLEM 5---------------------------
	 * smallest multiple */
	 public int problem5() {
		 int num = 20;
		 //2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder
		 while(true) {
			 int count = 0;
			 for(int i = 1; i < 21; i++) {
				 if(num % i == 0) {
					 count++;
				 }
			 }
			 if(count == 20) {
				 return num;
			 }
			 num++;
		 }
	 }
	 /*PROBLEM 6---------------------------
		 * Sum Square Difference */
	 public void problem6(int max) {
		 int sumSquares = 0;
		 int squareSum = 0;
		 for(int i = 1; i <= max; i++) {
			 sumSquares += i*i;
			 squareSum += i;
		 }
		 squareSum = squareSum * squareSum;
		 System.out.println(squareSum - sumSquares);
	 }
	 /*PROBLEM 7---------------------------
		 * 10001st prime */
	 public void problem7(int place) {
		 int currentPlace = 0;
		 int num = 1;
		 while(true) {
			 if(isPrime(num)) {
				 if(currentPlace == place) {
					 System.out.println("place " + place + " is prime number " + num);
					 return;
				 }
				 currentPlace++;
			 }
 			 num++;
		 }
	 }
	 /*PROBLEM 8---------------------------
		 * Largest product in a series */
	 public void problem8(int max) {
		 long product = 1;
		 long tempProduct = 1;
		 String n = "";
		 String thousNum = "73167176531330624919225119674426574742355349194934" + 
		 		"96983520312774506326239578318016984801869478851843" + 
		 		"85861560789112949495459501737958331952853208805511" + 
		 		"12540698747158523863050715693290963295227443043557" + 
		 		"66896648950445244523161731856403098711121722383113" + 
		 		"62229893423380308135336276614282806444486645238749" + 
		 		"30358907296290491560440772390713810515859307960866" + 
		 		"70172427121883998797908792274921901699720888093776" + 
		 		"65727333001053367881220235421809751254540594752243" + 
		 		"52584907711670556013604839586446706324415722155397" + 
		 		"53697817977846174064955149290862569321978468622482" + 
		 		"83972241375657056057490261407972968652414535100474" + 
		 		"82166370484403199890008895243450658541227588666881" + 
		 		"16427171479924442928230863465674813919123162824586" + 
		 		"17866458359124566529476545682848912883142607690042" + 
		 		"24219022671055626321111109370544217506941658960408" + 
		 		"07198403850962455444362981230987879927244284909188" + 
		 		"84580156166097919133875499200524063689912560717606" + 
		 		"05886116467109405077541002256983155200055935729725" + 
		 		"71636269561882670428252483600823257530420752963450";
		 for(int i = 0; i < thousNum.length() - max; i++) { //2091059712
			 	tempProduct = 1;
			 	String temp = "";
				 for(int j = 0; j < max; j++) {
					 tempProduct *= (thousNum.charAt(i + j) - '0');
					 temp += thousNum.charAt(i+j) + "";
				 }
			 if (tempProduct > product) {
				 product = tempProduct;
				 n = temp;
			 }
		 }
		 System.out.println("product is " + product);
		 System.out.println("product string is " + n);
	 }
} 
